### ISSUE TITLE
Requires 3 clicks on mobile to play video

### ISSUE THREAD

**Issue by jaskaran27** [Daugilas/lazyYT#4]
Tested on Google Chrome on an Android.

Since Android and iOS don't allow autoplay the user has to click twice to make the actual video play, but the recent update somehow required 3 clicks instead of 2.

**Comment by Daugilas** [comment]
@jaskaran27 could you please test version 1.2.1 (today's release)?

**Comment by jaskaran27** [comment]
@Daugilas Yeah, it fixes this. Thanks!
