### ISSUE TITLE
Low-res thumbnail image?

### ISSUE THREAD

**Issue by emwee** [Daugilas/lazyYT#7]
Hi,

I implemented this plugin to improve the load time of a page I'm working on; only to discover the thumbnail image that's picked when not setting a width (maxresdefault.jpg) is actually 462 kB, which is more than the JS filesize I was trying to avoid! Is there any way to optimize this?

Thanks!

**Comment by Daugilas** [comment]
@emwee I've dome some updates on how images are loaded. Could you please check if this problem persists?

**Comment by Daugilas** [comment]
Well, according to my demo's its selecting an image based on the actual video container size.
